[book]
authors = ["GeorgGrebenyuk"]
language = "ru"
multilingual = false
src = "content"
title = "Руководство разработчика AutoCAD .NET API"

[output.html]
no-section-label = true

[output.html.print]
enable = true
