[book]
authors = ["GeorgGrebenyuk"]
language = "ru"
multilingual = false
src = "content"
title = "Руководство разработчика AutoCAD Civil 3D .NET API"

[output.html]
no-section-label = true

[output.html.print]
enable = true
